fsm_node:
  fsm:
    swarm_en: false
    bench_en: false
    auto_pilot_en: false
    click_goal_en: true
    odom_goal_en: false
    #    odom_goal_topic: "/odom_goal"
#    click_goal_topic: "/goal"
    click_goal_topic: "/planning/click_goal"
    path_goal_topic: "/planning/path_goal"
    replan_rate: 15.0
    auto_pilot_speed: 3.0
    auto_pilot_yaw_speed: 1.0
    click_height: -999
    # if use the yaw ange in /goal as the goal yaw direction
    click_yaw_en: false
    cmd_topic: "/planning/pos_cmd"
    #    cmd_topic: "/quad_1/planning/pos_cmd"
    # mpc_cmd_type: 1 for PVAJ, 2 for poly traj
    mpc_cmd_type: 2
#    mpc_cmd_topic: "/planning_cmd/mpc"
    mpc_cmd_topic: "/planning_cmd/poly_traj"


  super_planner:
    print_log: false
    backup_traj_en: true
    frontend_in_known_free: true
    goal_vel_en: false
    visual_process: false
    use_fov_cut: false
    # 走廊生成的上限Bounding Box
    corridor_bound_dis: 1.2
    corridor_line_max_length: 2
    safe_corridor_line_max_length: 5
    iris_iter_num: 2
    obs_skip_num: 2
    # Replan时往前看多少秒
    replan_forward_dt: 0.1
    planning_horizon: 8
    receding_dis: 8
    # [WARN] the robot r should equal to decaymap resolution[0] * infalate dis.
    robot_r: 0.15
    yaw_dot_max: 3.0
    # Yaw mode: 1 heading to velocity, 2 heading to goal
    yaw_mode: 1


  traj_opt:
    swarm:
      enable: false
      swarm_clearance: -1
      penna_swarm: -1

    switch:
      save_log_en: false

    flatness:
      mass: 1.64
      dh: 0.35
      dv: 0.35
      cp: 0.001
      v_eps: 0.0001
      grav: 9.81

    boundary:
      max_vel: 1.0
      max_acc: 1.0
      max_jerk: 120.0
      max_omg: 2.5
      max_acc_thr: 17.0
      min_acc_thr: 6.0
      penna_margin: 0.05

    exp_traj:
      # for swarm
      pos_constraint_type: 2
      piece_num: 1
      block_energy_cost: false
      opt_accuracy: 2.0e-6
      integral_reso: 15
      smooth_eps: 0.01
      penna_t: 2.1e+3
      penna_pos: 2.0e+6
      penna_vel: 1.0e+6
      penna_acc: 1.0e+6
      penna_jerk: 1.0e+6 #
      penna_attract: -1.0e+6
      penna_omg: -1.0e+6
      penna_thr: -1.0e+6

    backup_traj:
      # for swarm
      pos_constraint_type: 1
      piece_num: 2
      block_energy_cost: true
      opt_accuracy: 1.0e-4
      integral_reso: 22
      smooth_eps: 0.01
      penna_t: 1.0e+2
      penna_ts: 1.0e+8
      penna_pos: 2.0e+9
      penna_vel: 1.0e+9
      penna_acc: 1.0e+9
      penna_jerk: -1.0e+6 #
      penna_attract: -1.0e+6
      penna_omg: -1.0e+9
      penna_thr: -1.0e+9

  astar:
    map_voxel_num: [ 500, 500, 100 ]
    visual_process: false
    allow_diag: true
    # 0 DIAG; 1 MANHATTAN; 2 EUCLIDEAN
    heu_type: 2
    debug_visualization_en: false

  rog_map:
    load_pcd_en: false
    pcd_name: "output.pcd"
    unk_inflation_en: false
    safe_margin: 0.0
    resolution: 0.05
    inflation_resolution: 0.15
    inflation_step: 1
    block_inf_pt: false
    map_size: [ 20,10,10 ]
    fix_map_origin: [ 0,0,2 ]
    # Virtual ceil and ground
    virtual_ceil_height: 999
    virtual_ground_height: -999

    map_sliding:
      enable: true
      # The minimum distance [m] to slide the map.
      threshold: 0.9
      # If the map rolling is disable, the map origin [m] should be set.


    frontier_extraction_en: false

    # If [enbale = true], the ROG-Map will actively take ros topic as input.
    #  else user should call function [updateMap] to update the map.
    ros_callback:
      enable: true
      cloud_topic: "/cloud_registered"
      odom_topic: "/lidar_slam/odom"
#      odom_topic: "/mavros/local_position/odom"
      odom_timeout: 2.0

    visulization:
      enbale: true
      # The rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
      time_rate: 2
      # The frame rate of visualization [Hz], if set to 0, the visualization will not be triggered by frame.
      frame_rate: 0
      # visualization range along the odom [m].
      range: [ 10, 10, 5 ]
      frame_id: "world"
      pub_unknown_map_en: true

    # Intensity filter for input point cloud. If the point intensity is less than this value,
    # it will be ignored (to avoid noise like dusk).
    intensity_thresh: -10
    # The temporal downsample rate for input point cloud.
    #  e.g. if set to k, the point cloud will be downsampled to 1/k.
    point_filt_num: 10

    # Probabilistc update
    raycasting:
      # if disable, the map will only maintain occupied information, and all other grid
      # will be considered as unknown.
      enable: true
      blind_filter_en: false

      batch_update_size: 1
      local_update_box: [ 30, 30, 5 ]
      # The range of raycasting [m].
      ray_range: [ 0.5, 30 ]

      p_min: 0.12
      p_miss: 0.4999
      p_free: 0.49999
      p_occ: 0.85
      p_hit: 0.9
      p_max: 0.98
      # The threshold of a non-occupied inf map grid to be considered as free. [0.0-1.0]
      # which means for a gird contains [u] unknown grids and [f] known free grids.
      # if [f/(f+u) > inf_map_known_free_thresh], the grid will be considered as free.
      #  e.g. this thresh is set to 1.0, it measn a inf map grid is considered as free only if all grids in it are known free.
      inf_map_known_free_thresh: 0.5